<div class="contentbox">
<form enctype="application/x-www-form-urlencoded" method="post" action="<?php echo $this->url() ?>">
    <?php echo $this->form->search ?>
    <?php echo $this->form->password ?>
    <?php echo $this->form->submit ?>
</form>
    
<?php

if (!empty($this->results)) {
    ?>
    <br><br><br>
    <?php
    foreach ($this->results as $result) { ?>
        <h3><a href="/report/view/session/<?php echo $result->session ?>" target="_blank"><?php echo $result->name ?></a></h3>
        <p><?php echo $result->contact_name ?> <?php echo $result->contact_forename ?><br><?php echo $result->email ?><br><?php echo $result->tel ?><br><?php echo $result->session ?>
        </p>
    <?php
    }
}

?>
    
</div>
