<style>
    .chartdiv {
        width: 230px;
        height: 150px;
        font-size: 11px;
        position: relative;
        float: left;

    }
    .chartdivBig {
        width: 250px;
        height: 200px;
        font-size: 11px;
        position: relative;
        float: left;
    }
</style>

<script type="text/javascript" src="<?php echo $this->location() ?>/public/amcharts/amcharts.js"></script>
<script type="text/javascript" src="<?php echo $this->location() ?>/public/amcharts/gauge.js"></script>


<script language="JavaScript">
    var gaugeChart = AmCharts.makeChart("chartdivAlgemeen", {
        "type": "gauge",
        "theme": "none",
        "axes": [
            {
                "axisThickness": 3,
                "axisAlpha": 0.5,
                "tickAlpha": 0.5,
                "valueInterval": 10,
                "bands": [
                    {
                        "color": "#cc4748",
                        "endValue": 30,
                        "startValue": 0
                    },
                    {
                        "color": "#E99507",
                        "endValue": 60,
                        "startValue": 30
                    },
                    {
                        "color": "#84b761",
                        "endValue": 100,
                        "innerRadius": "95%",
                        "startValue": 60
                    }
                ],
                "bottomText": "QUICK SCAN",
                "bottomTextYOffset": 20,
                "endValue": 100
            }
        ],
        "arrows": [
            {
                "value" : <?php echo $this->result['categories']['mainscore']; ?>
            }
        ]
    });
</script>
<script language="JavaScript">
<?php  $i=0; foreach ($this->result['categories'] as $category => $result) { if ($category!='mainscore') { $i++; ?>
    var gaugeChart = AmCharts.makeChart("chartdiv<?php echo $i ?>", {
        "type": "gauge",
        "theme": "none",
        "axes": [
            {
                "axisThickness": 1,
                "axisAlpha": 0.2,
                "tickAlpha": 0.2,
                "valueInterval": 20,
                "bands": [
                    {
                        "color": "#cc4748",
                        "endValue": 30,
                        "startValue": 0
                    },
                    {
                        "color": "#E99507",
                        "endValue": 60,
                        "startValue": 30
                    },
                    {
                        "color": "#84b761",
                        "endValue": 100,
                        "innerRadius": "95%",
                        "startValue": 60
                    }
                ],
                "bottomText": "<?php echo $category ?>",
                "bottomTextYOffset": 20,
                "endValue": 100
            }
        ],
        "arrows": [
            {
                "value" : <?php echo $result['score_total']; ?>
            }
        ]
    });
    <?php }} ?>
</script>
<div class="contentbox">
<br>
    <h1 style="text-align: center">RAPPORT QUICK SCAN</h1>
<h2><?php echo $this->result['general']->name ?></h2>
<p><?php echo $this->T("aangemaakt_op")?> <?php echo $this->Date($this->result['general']->created)?> <?php if ($this->result['general']->vatnr) { ?> <?php echo "<br>".$this->result['general']->vatnr ?> <?php } ?>
<br><?php echo $this->T("contactpersoon")?> : <?php echo $this->result['general']->contact_name ?> <?php echo $this->result['general']->contact_forename ?>
<br>E-mail : <?php echo $this->result['general']->email ?>
<br>Tel : <?php echo $this->result['general']->tel ?>
</p>
<br><br>

<table>
    <tr>
        <td align="right"><div id="chartdiv1" class="chartdiv"></div>
            <br><br><br><div id="chartdiv2"  class="chartdiv"></div>
        </td>
        <td align="center"><div id="chartdivAlgemeen" class="chartdivBig"></div>
        </td>
        <td align="left"><div id="chartdiv3"  class="chartdiv"></div>
            <br><br><br><div id="chartdiv4"  class="chartdiv"></div>
        </td>
    </tr>
</table>
    <br><br><br>
    <?php foreach ($this->result['categories'] as $category => $scores ) { if ($category!='mainscore') { ?>
        <h2><?php echo $category ?></h2>
        <?php echo $this->T("U_behaalde_een_score_van")?> <?php echo $this->Amount($scores['score_total'])?>% <?php echo $this->T("voor_deze_peiler")?>.<br><br>
    <?php } } ?>
    <h2><?php echo $this->T("U_behaalde_een_algemene_score_van")?> <?php echo $this->Amount($this->result['categories']['mainscore']) ?>%.<br></h2>
    <p style="page-break-after:always;"></p>
    <table width="100%">
        <tr>
            <td><img class="logo" height=65 src="<?php echo $this->Location(); ?>/public/images/logoBig.png"
                     onclick="window.location.href='<?php echo $this->Location(); ?>'">
            </td>
            <td align="right"><span class="titleBig">QUICK SCAN</span><br><span
                    class="title">Triple A Solutions</span><br></td>
        </tr>
    </table>

    <?php
foreach ($this->answers as $category => $questions) { $i = 0; ?>
<br>
<h2><?php echo $category ?></h2><br>
    <?php foreach ($questions  as $question) {  $i++;?>
        <li><i><?php echo $question['question'] ?></i>&nbsp;&nbsp;<strong><?php echo $question['answer'] ?></strong></li>
    <?php } ?>
<?php } ?>
    <br><br>
</div>

