<table class="contentbox" width="100%">
        <tr>
            <td align="center">
                This application is currently under construction. Please come back later.
<!--
                <p><a href="<?php echo $this->location()?>/index/code/selectlang/nl" style="width:80%">Start analyse (NL)</a></p>
                <p><a href="<?php echo $this->location()?>/index/code/selectlang/fr" style="width:80%">Démarrez l'analyse (FR)</a></p>
                <p><a href="<?php echo $this->location()?>/index/code/selectlang/en" style="width:80%">Start analysis (EN)</a></p>
-->
            <br><br><img class="logo" style="width: 80%"  src="<?php echo $this->Location(); ?>/public/images/report.png"></td>
        </tr>
</table>
