<table class="contentbox" width="100%">
        <tr>
            <td align="center">
                <p><a href="<?php echo $this->location()?>/index/questions/selectlang/nl" style="width:80%">Gratis analyse</a></p>
                <p><a href="<?php echo $this->location()?>/index/questions/selectlang/fr" style="width:80%">Analyse gratuite</a></p>
                <p><a href="<?php echo $this->location()?>/index/questions/selectlang/en" style="width:80%">Free report</a></p>

            <br><br><img class="logo" style="width: 80%"  src="<?php echo $this->Location(); ?>/public/images/report.png"></td>
        </tr>
</table>
