<table class="contentbox" width="100%">
        <tr>
            <td align="center">
                <i>"To improve is to change; to be perfect is to change often." - Winston Churchill</i><br><br>
                <p>Wij hebben voor u een professionele Credit Scan ontwikkeld.
                    Door te peilen naar hoe uw onderneming omgaat met de organisatie en het management van de processen mbt het credit management krijgen wij inzicht in de huidige situatie.
                    Op basis van de resultaten hiervan geven wij advies hoe de procesvoering verbeterd kan worden om een optimale cashflow te bereiken.
                    U bepaalt uiteraard zelf het verdere verloop.<br><br><a href="<?php echo $this->location()?>/index/code/selectlang/nl" style="width:80%">Start analyse</a>
                </p>
                <p>Notre Credit Scan a été conçu afin de vous donner une image claire de votre politique de crédit.
                    Nous vous donnons des conseils sur la façon dont vos processus internes peuvent être améliorés pour atteindre des flux de trésorerie optimale et optimaliser votre cash-flow.
                    Mais au final, c'est vous qui décidez du développement de nos conseils.<br><br><a href="<?php echo $this->location()?>/index/code/selectlang/fr" style="width:80%">Démarrez l'analyse</a><br>

                </p>
                <p>We have developed a professional Credit Scan for you.
                    By testing how your company deals with the organization and the management of the processes related to credit management we understand the current situation of your company.
                    Based on the results we give advice on how the current situation could be improved to achieve optimal cash flow.
                    But in the end it is up to you where we go from there.<br><br><a href="<?php echo $this->location()?>/index/code/selectlang/en" style="width:80%">Start analysis</a></p>

            <br><br></td>
        </tr>
</table>
