<script>
    $(function() {
        $( "#accordion" ).accordion({
            heightStyle: "content"
        });
    });
    function openNextAccordionPanel() {
        var current = $( "#accordion" ).accordion("option","active"),
            maximum = $( "#accordion" ).find("h3").length,
            next = current+1 === maximum ? 0 : current+1;
        $( "#accordion" ).accordion("option","active",next);
        $('html,body').scrollTop(0);
    }
</script>
<div class="contentbox">
    <form enctype="application/x-www-form-urlencoded" method="post" action="<?php echo $this->Location()?>/index/questions">
        <h1><?php echo $this->T("vragenlijst")?></h1>
        <p><?php echo $this->T("vulin")?></p>
        <?php if ($this->showError) {
            print $this->Error($this->G('nietvolledig'));
        } ?>

        <div id="accordion">
            <?php if (!empty($this->themes)) { $counter = count($this->themes); $i = 0; foreach ($this->themes as $theme) {  $i++; ?>

                <h3><?php echo $theme->theme ?></h3>
                <div class='showable'>
                    <?php if (!empty($this->questions[$theme->theme])) { foreach ($this->questions[$theme->theme] as $id => $question) { ?>
                        <p>
                            <dt <?php if (in_array($id, $this->incompleteQuestions)) echo "class='errorfield'"; ?> ><?php echo $question['question'] ?></dt>
                        <dd><?php if (!empty($question['answer1'])) { ?><label><input type="radio" name="question[<?php echo $id?>]" id="question<?php echo $id?>-1" value='1' <?php if ($this->answers[$id] == '1') echo "checked"; ?> ><?php echo $question['answer1'] ?></label><?php } ?>
                            <br><?php if (!empty($question['answer2'])) { ?><label><input type="radio" name="question[<?php echo $id?>]" id="question<?php echo $id?>-2" value='2' <?php if ($this->answers[$id] == '2') echo "checked"; ?>><?php echo $question['answer2'] ?></label><?php } ?>
                            <br><?php if (!empty($question['answer3'])) { ?><label><input type="radio" name="question[<?php echo $id?>]" id="question<?php echo $id?>-3" value='3' <?php if ($this->answers[$id] == '3') echo "checked"; ?>><?php echo $question['answer3'] ?></label><?php } ?>
                            <br><?php if (!empty($question['answer4'])) { ?><label><input type="radio" name="question[<?php echo $id?>]" id="question<?php echo $id?>-4" value='4' <?php if ($this->answers[$id] == '4') echo "checked"; ?>><?php echo $question['answer4'] ?></label><?php } ?>
                        </dd>
                        </p>
                    <?php }} ?>
                    <?php if ($i<$counter) { ?>
                    <input type="button" class="submit" value="<?php echo $this->T("volgende")?>"  onclick="openNextAccordionPanel();">
                    <?php } ?>
                    <br>&nbsp;
                </div>
            <?php } }?>
        </div>
        <input type="hidden" name="session" id="session" value="<?php echo $this->session?>">
        <br><br><input type="submit" class="submit" name="submit" value="<?php echo $this->T("opslaan")?>">
    </form>
</div>

