<style>
    .chartdiv {
        width: 230px;
        height: 150px;
        font-size: 11px;
        position: relative;
        float: left;

    }
    .chartdivBig {
        width: 250px;
        height: 200px;
        font-size: 11px;
        position: relative;
        float: left;
    }
</style>

<script type="text/javascript" src="<?php echo $this->location() ?>/public/amcharts/amcharts.js"></script>
<script type="text/javascript" src="<?php echo $this->location() ?>/public/amcharts/gauge.js"></script>


<script language="JavaScript">
    var gaugeChart = AmCharts.makeChart("chartdivAlgemeen", {
        "type": "gauge",
        "theme": "none",
        "axes": [
            {
                "axisThickness": 3,
                "axisAlpha": 0.5,
                "tickAlpha": 0.5,
                "valueInterval": 10,
                "bands": [
                    {
                        "color": "#cc4748",
                        "endValue": 60,
                        "startValue": 0
                    },
                    {
                        "color": "#84b761",
                        "endValue": 100,
                        "innerRadius": "95%",
                        "startValue": 60
                    }
                ],
                "bottomText": "QUICK SCAN",
                "bottomTextYOffset": 20,
                "endValue": 100
            }
        ],
        "arrows": [
            {
                "value" : <?php echo $this->result['categories']['mainscore']; ?>
            }
        ]
    });
</script>
<script language="JavaScript">
<?php  $i=0; foreach ($this->result['categories'] as $category => $result) { if ($category!='mainscore') { $i++; ?>
    var gaugeChart = AmCharts.makeChart("chartdiv<?php echo $i ?>", {
        "type": "gauge",
        "theme": "none",
        "axes": [
            {
                "axisThickness": 1,
                "axisAlpha": 0.2,
                "tickAlpha": 0.2,
                "valueInterval": 20,
                "bands": [
                    {
                        "color": "#cc4748",
                        "endValue": 60,
                        "startValue": 0
                    },
                    {
                        "color": "#84b761",
                        "endValue": 100,
                        "innerRadius": "95%",
                        "startValue": 60
                    }
                ],
                "bottomText": "<?php echo $category ?>",
                "bottomTextYOffset": 20,
                "endValue": 100
            }
        ],
        "arrows": [
            {
                "value" : <?php echo $result['score_total']; ?>
            }
        ]
    });
    <?php }} ?>
</script>
<div class="contentbox">
<h1><?php echo $this->result['general']->name?></h1>
<p><?php echo $this->T("aangemaakt_op")?> <?php echo $this->Date($this->result['general']->created)?> voor <?php echo $this->result['general']->name ?> (<?php echo $this->result['general']->vatnr ?>)
<br><?php echo $this->T("contactpersoon")?> : <?php echo $this->result['general']->contact_name ?> <?php echo $this->result['general']->contact_forename ?>
<br><?php echo $this->T("email")?> :  <?php echo $this->result['general']->email ?>
<br><?php echo $this->T("tel_mobiel")?> :  <?php echo $this->result['general']->tel ?>
</p>

<table>
    <tr>
        <td align="right"><div id="chartdiv1" class="chartdiv"></div>
            <br><br><br><div id="chartdiv2"  class="chartdiv"></div>
        </td>
        <td align="center"><div id="chartdivAlgemeen" class="chartdivBig"></div>
        </td>
        <td align="left"><div id="chartdiv3"  class="chartdiv"></div>
            <br><br><br><div id="chartdiv4"  class="chartdiv"></div>
        </td>
    </tr>
</table>
    <h2><?php echo $this->T("verklaring")?></h2>
    <h3><?php echo $this->T("general_score")?></h3>
    <?php echo $this->T("U_behaalde_een_score_van")?> <?php echo $this->result['categories']['mainscore'] ?>%.
    <br><br>
    <?php
    foreach ($this->result['categories'] as $category => $result) { if ($category!='mainscore') {
        ?>
        <h3><?php echo $category ?></h3>
        <p><?php echo $this->T("U_behaalde_een_score_van")?> <?php echo $result['score_total'] ?>% <?php echo $this->T("voor_deze_peiler")?>.</p>
    <?php
    }}
    ?>
</div>
